#!/usr/bin/env bash

set -euxo pipefail

ZLIB_REPO_URL="https://github.com/madler/zlib"
VERSION="1.3.1"
BRANCH="v${VERSION}"

BUILD_DIR=".build"
INSTALL_DIR="/opt/zlib"
OUT_DIR=".out"

NICE="nice -19 ionice -c2 -n5"
JOBS="${JOBS:=$(($(nproc --all) + 2))}"

build_time="$(date '+%Y%m%d%H%M%S')"

function abspath() {
  readlink -m "$1"
}

function log() {
  tee -a "${1}" | stdbuf -oL grep --color=always -iE "error|fail|cannot|can't|unable|"
}

function package() {
  local input_dir="${1}"
  local output_tarball="${2}"

  ${NICE} find "${input_dir}" -printf "%P\n" \
    | ${NICE} tar --no-recursion -cf - -C "${input_dir}" --files-from=- \
    | ${NICE} xz -T0 -k > "${output_tarball}"
}

build_dir="$(abspath ${BUILD_DIR})"
mkdir -p "${build_dir}"
outdir="$(abspath "${OUT_DIR}")"
mkdir -p "${outdir}"

pushd "$build_dir" >/dev/null
  src_dir="zlib-${BRANCH}"

  if [ ! -d "${src_dir}" ]; then
    git clone --recursive --depth=100 -b "${BRANCH}" "${ZLIB_REPO_URL}" "${src_dir}"
  fi

  pushd "${src_dir}" >/dev/null
    ${NICE} ./configure \
      --prefix="${INSTALL_DIR}" \
      --static \
      2>&1 | log "build.log"

    ${NICE} make -j"${JOBS}" 2>&1 | log "build.log"
    ${NICE} make install 2>&1 | log "build.log"

    sed -i "s|prefix=${INSTALL_DIR}|prefix=\$\{pcfiledir\}/../..|g" "${INSTALL_DIR}/lib/pkgconfig/zlib.pc"

    cp "build.log" "${INSTALL_DIR}/"

    package "${INSTALL_DIR}" "${outdir}/zlib-${VERSION}-static-${build_time}.tar.xz"
  popd >/dev/null
popd >/dev/null

